export const country = [
  { value: 'AF', label: 'Afganistán' },
  { value: 'AL', label: 'Albania' },
  { value: 'DE', label: 'Alemania' },
  { value: 'AD', label: 'Andorra' },
  { value: 'AO', label: 'Angola' },
  { value: 'AI', label: 'Anguila' },
  { value: 'AQ', label: 'Antártida' },
  { value: 'AG', label: 'Antigua y Barbuda' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AM', label: 'Armenia' },
  { value: 'AW', label: 'Aruba' },
  { value: 'AU', label: 'Australia' },
  { value: 'AT', label: 'Austria' },
  { value: 'AZ', label: 'Azerbaiyán' },
  { value: 'BS', label: 'Bahamas' },
  { value: 'BH', label: 'Baréin' },
  { value: 'BD', label: 'Bangladés' },
  { value: 'BB', label: 'Barbados' },
  { value: 'BY', label: 'Bielorrusia' },
  { value: 'BE', label: 'Bélgica' },
  { value: 'BZ', label: 'Belice' },
  { value: 'BJ', label: 'Benín' },
  { value: 'BM', label: 'Bermudas' },
  { value: 'BT', label: 'Bután' },
  { value: 'BO', label: 'Bolivia' },
  { value: 'BA', label: 'Bosnia y Herzegovina' },
  { value: 'BW', label: 'Botsuana' },
  { value: 'BR', label: 'Brasil' },
  { value: 'BN', label: 'Brunéi' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'BF', label: 'Burkina Faso' },
  { value: 'BI', label: 'Burundi' },
  { value: 'CV', label: 'Cabo Verde' },
  { value: 'KH', label: 'Camboya' },
  { value: 'CM', label: 'Camerún' },
  { value: 'CA', label: 'Canadá' },
  { value: 'CL', label: 'Chile' },
  { value: 'CN', label: 'China' },
  { value: 'CY', label: 'Chipre' },
  { value: 'CO', label: 'Colombia' },
  { value: 'KM', label: 'Comoras' },
  { value: 'CG', label: 'Congo' },
  { value: 'CD', label: 'Congo (Rep. Dem.)' },
  { value: 'KR', label: 'Corea del Sur' },
  { value: 'KP', label: 'Corea del Norte' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'CI', label: 'Costa de Marfil' },
  { value: 'HR', label: 'Croacia' },
  { value: 'CU', label: 'Cuba' },
  { value: 'DK', label: 'Dinamarca' },
  { value: 'DM', label: 'Dominica' },
  { value: 'EC', label: 'Ecuador' },
  { value: 'EG', label: 'Egipto' },
  { value: 'SV', label: 'El Salvador' },
  { value: 'AE', label: 'Emiratos Árabes Unidos' },
  { value: 'ER', label: 'Eritrea' },
  { value: 'SK', label: 'Eslovaquia' },
  { value: 'SI', label: 'Eslovenia' },
  { value: 'ES', label: 'España' },
  { value: 'US', label: 'Estados Unidos' },
  { value: 'EE', label: 'Estonia' },
  { value: 'ET', label: 'Etiopía' },
  { value: 'PH', label: 'Filipinas' },
  { value: 'FI', label: 'Finlandia' },
  { value: 'FJ', label: 'Fiyi' },
  { value: 'FR', label: 'Francia' },
  { value: 'GA', label: 'Gabón' },
  { value: 'GM', label: 'Gambia' },
  { value: 'GE', label: 'Georgia' },
  { value: 'GH', label: 'Ghana' },
  { value: 'GI', label: 'Gibraltar' },
  { value: 'GD', label: 'Granada' },
  { value: 'GR', label: 'Grecia' },
  { value: 'GL', label: 'Groenlandia' },
  { value: 'GP', label: 'Guadalupe' },
  { value: 'GU', label: 'Guam' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'GY', label: 'Guyana' },
  { value: 'GF', label: 'Guayana Francesa' },
  { value: 'GN', label: 'Guinea' },
  { value: 'GQ', label: 'Guinea Ecuatorial' },
  { value: 'GW', label: 'Guinea-Bisáu' },
  { value: 'HT', label: 'Haití' },
  { value: 'HN', label: 'Honduras' },
  { value: 'HU', label: 'Hungría' },
  { value: 'IN', label: 'India' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IR', label: 'Irán' },
  { value: 'IQ', label: 'Irak' },
  { value: 'IE', label: 'Irlanda' },
  { value: 'IS', label: 'Islandia' },
  { value: 'IL', label: 'Israel' },
  { value: 'IT', label: 'Italia' },
  { value: 'JM', label: 'Jamaica' },
  { value: 'JP', label: 'Japón' },
  { value: 'JO', label: 'Jordania' },
  { value: 'KZ', label: 'Kazajistán' },
  { value: 'KE', label: 'Kenia' },
  { value: 'KG', label: 'Kirguistán' },
  { value: 'KI', label: 'Kiribati' },
  { value: 'KW', label: 'Kuwait' },
  { value: 'LA', label: 'Laos' },
  { value: 'LS', label: 'Lesoto' },
  { value: 'LV', label: 'Letonia' },
  { value: 'LB', label: 'Líbano' },
  { value: 'LR', label: 'Liberia' },
  { value: 'LY', label: 'Libia' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Lituania' },
  { value: 'LU', label: 'Luxemburgo' },
  { value: 'MK', label: 'Macedonia del Norte' },
  { value: 'MG', label: 'Madagascar' },
  { value: 'MY', label: 'Malasia' },
  { value: 'MW', label: 'Malaui' },
  { value: 'MV', label: 'Maldivas' },
  { value: 'ML', label: 'Malí' },
  { value: 'MT', label: 'Malta' },
  { value: 'MA', label: 'Marruecos' },
  { value: 'MQ', label: 'Martinica' },
  { value: 'MU', label: 'Mauricio' },
  { value: 'MR', label: 'Mauritania' },
  { value: 'MX', label: 'México' },
  { value: 'FM', label: 'Micronesia' },
  { value: 'MD', label: 'Moldavia' },
  { value: 'MC', label: 'Mónaco' },
  { value: 'MN', label: 'Mongolia' },
  { value: 'ME', label: 'Montenegro' },
  { value: 'MZ', label: 'Mozambique' },
  { value: 'NA', label: 'Namibia' },
  { value: 'NR', label: 'Nauru' },
  { value: 'NP', label: 'Nepal' },
  { value: 'NI', label: 'Nicaragua' },
  { value: 'NE', label: 'Níger' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'NO', label: 'Noruega' },
  { value: 'NZ', label: 'Nueva Zelanda' },
  { value: 'OM', label: 'Omán' },
  { value: 'NL', label: 'Países Bajos' },
  { value: 'PK', label: 'Pakistán' },
  { value: 'PW', label: 'Palaos' },
  { value: 'PA', label: 'Panamá' },
  { value: 'PG', label: 'Papúa Nueva Guinea' },
  { value: 'PY', label: 'Paraguay' },
  { value: 'PE', label: 'Perú' },
  { value: 'PL', label: 'Polonia' },
  { value: 'PT', label: 'Portugal' },
  { value: 'QA', label: 'Catar' },
  { value: 'GB', label: 'Reino Unido' },
  { value: 'CF', label: 'República Centroafricana' },
  { value: 'CZ', label: 'República Checa' },
  { value: 'DO', label: 'República Dominicana' },
  { value: 'RW', label: 'Ruanda' },
  { value: 'RO', label: 'Rumanía' },
  { value: 'RU', label: 'Rusia' },
  { value: 'WS', label: 'Samoa' },
  { value: 'KN', label: 'San Cristóbal y Nieves' },
  { value: 'SM', label: 'San Marino' },
  { value: 'VC', label: 'San Vicente y las Granadinas' },
  { value: 'LC', label: 'Santa Lucía' },
  { value: 'ST', label: 'Santo Tomé y Príncipe' },
  { value: 'SN', label: 'Senegal' },
  { value: 'RS', label: 'Serbia' },
  { value: 'SC', label: 'Seychelles' },
  { value: 'SL', label: 'Sierra Leona' },
  { value: 'SG', label: 'Singapur' },
  { value: 'SY', label: 'Siria' },
  { value: 'SO', label: 'Somalia' },
  { value: 'LK', label: 'Sri Lanka' },
  { value: 'ZA', label: 'Sudáfrica' },
  { value: 'SD', label: 'Sudán' },
  { value: 'SS', label: 'Sudán del Sur' },
  { value: 'SE', label: 'Suecia' },
  { value: 'CH', label: 'Suiza' },
  { value: 'SR', label: 'Surinam' },
  { value: 'TH', label: 'Tailandia' },
  { value: 'TZ', label: 'Tanzania' },
  { value: 'TJ', label: 'Tayikistán' },
  { value: 'TL', label: 'Timor Oriental' },
  { value: 'TG', label: 'Togo' },
  { value: 'TO', label: 'Tonga' },
  { value: 'TT', label: 'Trinidad y Tobago' },
  { value: 'TN', label: 'Túnez' },
  { value: 'TM', label: 'Turkmenistán' },
  { value: 'TR', label: 'Turquía' },
  { value: 'TV', label: 'Tuvalu' },
  { value: 'UA', label: 'Ucrania' },
  { value: 'UG', label: 'Uganda' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'UZ', label: 'Uzbekistán' },
  { value: 'VU', label: 'Vanuatu' },
  { value: 'VA', label: 'Ciudad del Vaticano' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Vietnam' },
  { value: 'YE', label: 'Yemen' },
  { value: 'ZM', label: 'Zambia' },
  { value: 'ZW', label: 'Zimbabue' }
];

export const states = [
  { value: 'AGU', label: 'Aguascalientes' },
  { value: 'BCN', label: 'Baja California' },
  { value: 'BCS', label: 'Baja California Sur' },
  { value: 'CAM', label: 'Campeche' },
  { value: 'CHP', label: 'Chiapas' },
  { value: 'CHH', label: 'Chihuahua' },
  { value: 'COA', label: 'Coahuila de Zaragoza' },
  { value: 'COL', label: 'Colima' },
  { value: 'CMX', label: 'Ciudad de México' },
  { value: 'DUR', label: 'Durango' },
  { value: 'GUA', label: 'Guanajuato' },
  { value: 'GRO', label: 'Guerrero' },
  { value: 'HID', label: 'Hidalgo' },
  { value: 'JAL', label: 'Jalisco' },
  { value: 'MEX', label: 'México' },
  { value: 'MIC', label: 'Michoacán de Ocampo' },
  { value: 'MOR', label: 'Morelos' },
  { value: 'NAY', label: 'Nayarit' },
  { value: 'NLE', label: 'Nuevo León' },
  { value: 'OAX', label: 'Oaxaca' },
  { value: 'PUE', label: 'Puebla' },
  { value: 'QUE', label: 'Querétaro' },
  { value: 'ROO', label: 'Quintana Roo' },
  { value: 'SLP', label: 'San Luis Potosí' },
  { value: 'SIN', label: 'Sinaloa' },
  { value: 'SON', label: 'Sonora' },
  { value: 'TAB', label: 'Tabasco' },
  { value: 'TAM', label: 'Tamaulipas' },
  { value: 'TLA', label: 'Tlaxcala' },
  { value: 'VER', label: 'Veracruz de Ignacio de la Llave' },
  { value: 'YUC', label: 'Yucatán' },
  { value: 'ZAC', label: 'Zacatecas' }

];

export const sector = [
  { value: 'Tecnología e informática', label: 'Tecnología e informática' },
  { value: 'Comercio y ventas', label: 'Comercio y ventas' },
  { value: 'Construcción e Inmobiliaria', label: 'Construcción e Inmobiliaria' },
  { value: 'Manufactura e industria', label: 'Manufactura e industria' },
  { value: 'Transporte y logística', label: 'Transporte y logística' },
];

export const countryCodes = [
  { label: '+52 (MX)', value: '+52' },
  { label: '+1 (US)', value: '+1' },
];

export const educationLevels = [
  { value: 'PREESCOLAR', label: 'Preescolar' },
  { value: 'PRIMARIA', label: 'Primaria' },
  { value: 'SECUNDARIA', label: 'Secundaria' },
  { value: 'BACHILLERATO_GENERAL', label: 'Bachillerato General' },
  { value: 'CARRERA_TECNICA', label: 'Carrera Técnica' },
  { value: 'LICENCIATURA', label: 'Licenciatura' },
  { value: 'INGENIERIA', label: 'Ingeniería' },
  { value: 'MAESTRIA', label: 'Maestría' },
  { value: 'DOCTORADO', label: 'Doctorado' },
  { value: 'POSDOCTORADO', label: 'Posdoctorado' },
];